# Generated by Django 6.0.4 on 2026-04-28 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_resultado', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('fuente', models.CharField(default='modelo_vision', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='cultivos.cultivo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='lotes.lote')),
            ],
        ),
    ]
