# Generated by assistant: add choices to tipo_resultado
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='tipo_resultado',
            field=models.CharField(choices=[('cantidad_frutos', 'Cantidad de frutos'), ('frutos_maduros', 'Frutos maduros'), ('estimacion_cosecha', 'Estimación de cosecha'), ('porcentaje_madurez', 'Porcentaje de madurez')], max_length=100),
        ),
    ]
