# Generated by Django 6.0.4 on 2026-08-06 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0004_remove_drive_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='cantidad_frutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='cantidad_imagenes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analisis',
            name='estimacion_cosecha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='frutos_maduros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='mensaje_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='porcentaje_madurez',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='origen',
            field=models.CharField(choices=[('manual', 'Subida manual'), ('repositorio', 'Repositorio (Cloudinary)')], max_length=20),
        ),
    ]
