# Generated by Django 6.0.4 on 2026-08-24 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0005_analisis_cantidad_frutos_analisis_cantidad_imagenes_and_more'),
        ('repository', '0003_repositorioimagen_imagenrepositorio_repositorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis', to='repository.repositorioimagen'),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
    ]
