# Generated by Django 6.0.4 on 2026-08-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0006_analisis_repositorio_alter_analisis_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('procesado_con_errores', 'Procesado con errores'), ('error', 'Error')], default='pendiente', max_length=25),
        ),
    ]
