# Generated by Django 6.0.4 on 2026-08-05 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0002_cultivo_latitud_cultivo_longitud'),
        ('lotes', '0002_lote_ancho_lote_largo_lote_latitud_lote_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=255, unique=True)),
                ('public_id', models.CharField(max_length=500, unique=True)),
                ('secure_url', models.URLField(max_length=1000)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('formato', models.CharField(blank=True, max_length=20)),
                ('ancho', models.PositiveIntegerField(blank=True, null=True)),
                ('alto', models.PositiveIntegerField(blank=True, null=True)),
                ('tamano_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('procesando', 'Procesando'), ('error', 'Error')], default='disponible', max_length=20)),
                ('procesada', models.BooleanField(default=False)),
                ('fecha_sincronizacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_repositorio', to='cultivos.cultivo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_repositorio', to='lotes.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_repositorio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_sincronizacion'],
            },
        ),
    ]
