# Generated by Django 6.0.4 on 2026-08-06 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0005_analisis_cantidad_frutos_analisis_cantidad_imagenes_and_more'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenrepositorio',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='metricas.analisis'),
        ),
        migrations.AlterField(
            model_name='imagenrepositorio',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('procesando', 'Procesando'), ('procesada', 'Procesada'), ('error', 'Error')], default='disponible', max_length=20),
        ),
    ]
