# Generated by Django 6.0.4 on 2026-08-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_imagenrepositorio_analisis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositorioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('proveedor', models.CharField(choices=[('CLOUDINARY', 'Cloudinary')], default='CLOUDINARY', max_length=20)),
                ('cloud_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret_cifrado', models.TextField()),
                ('carpeta_raiz', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=False)),
                ('estado_conexion', models.CharField(choices=[('sin_probar', 'Sin probar'), ('conectado', 'Conectado'), ('fallido', 'Fallido')], default='sin_probar', max_length=20)),
                ('ultimo_sync', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositorios_imagen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='imagenrepositorio',
            name='repositorio',
            field=models.ForeignKey(blank=True, help_text='Null en filas sincronizadas antes de existir configuración por usuario (fallback global).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='repository.repositorioimagen'),
        ),
        migrations.AddConstraint(
            model_name='repositorioimagen',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario',), name='unico_repositorio_activo_por_usuario'),
        ),
    ]
