# Generated by Django 6.0.4 on 2026-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_repositorioimagen_imagenrepositorio_repositorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenrepositorio',
            name='asset_folder',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='imagenrepositorio',
            name='fecha_creacion_cloudinary',
            field=models.DateTimeField(blank=True, help_text='created_at reportado por Cloudinary para este asset.', null=True),
        ),
        migrations.AddField(
            model_name='imagenrepositorio',
            name='resource_type',
            field=models.CharField(blank=True, default='image', max_length=20),
        ),
    ]
