# Generated by Django 6.0.4 on 2026-04-28 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_fruto', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('area_sembrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_siembra', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
