# Generated by Django 6.0.4 on 2026-06-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpeta_url', models.URLField(blank=True, max_length=500)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Drive',
                'verbose_name_plural': 'Configuración de Drive',
            },
        ),
    ]
