# Generated by Django 6.0.4 on 2026-08-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_repositorio_interno_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenCultivo',
        ),
    ]
