"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import cloudinary
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variables de entorno (.env no se versiona — ver .env.example).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7^58#p$dbuxo5yg%-yvz5-^+gex^9&qk=vxr(uoz)@!40*=u76'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'testserver',  # requerido por el test client de Django (manage.py test)
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'authtoken',
    'cultivos',
    'lotes',
    'metricas',
    'archivos',
    'ml_models',
    'ubicaciones',
    'repository',
    'geolocation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'monitoreo_db',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

ML_CHECKPOINTS_DIR = BASE_DIR / 'ml_models' / 'checkpoints'

# CORS settings for local frontend development.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# Optional during local development if you later use session-authenticated requests.
CORS_ALLOW_CREDENTIALS = True

# Authentication redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Sesión Django
SESSION_COOKIE_HTTPONLY = True       # La cookie no es accesible desde JavaScript
SESSION_COOKIE_SAMESITE = "Lax"     # localhost cross-port comparte registrable domain → funciona
SESSION_COOKIE_SECURE = False        # Solo desarrollo — cambiar a True en producción con HTTPS
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 días en segundos

# CSRF — orígenes de confianza para requests cross-origin con credenciales
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Cloudinary — repositorio externo de imágenes (ver app 'repository').
# Las claves viven únicamente aquí (backend); nunca se exponen al frontend.
#
# Estas variables son OPCIONALES: cada usuario configura su propio
# repositorio desde la interfaz (modelo RepositorioImagen, cifrado en BD).
# Si se completan aquí, actúan solo como repositorio de fallback para
# usuarios que todavía no configuraron uno propio — ver
# repository/providers/factory.py::get_provider_for_user(). Un despliegue
# nuevo puede dejarlas vacías sin que el sistema falle al arrancar.
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '')

# CLOUDINARY_DEFAULT_FOLDER: valor inicial opcional para el repositorio de
# fallback de arriba — no es la fuente de verdad de "qué carpeta sincronizar".
# La carpeta real se elige desde la interfaz (selector "Actualizar carpetas"
# en el módulo Repositorio, que consulta Cloudinary en vivo) y se guarda por
# usuario en RepositorioImagen.carpeta_raiz (PostgreSQL) — crear una carpeta
# nueva en Cloudinary y sincronizarla nunca requiere tocar este .env ni
# reiniciar el backend. Se acepta también el nombre histórico
# CLOUDINARY_FOLDER para no romper despliegues existentes.
CLOUDINARY_FOLDER = os.environ.get('CLOUDINARY_DEFAULT_FOLDER') or os.environ.get('CLOUDINARY_FOLDER', 'agrovision')

# Clave de cifrado dedicada para RepositorioImagen.api_secret (opcional).
# Si se omite, se deriva de SECRET_KEY (ver repository/encryption.py) — fijar
# una propia en producción permite rotar SECRET_KEY sin perder los secretos
# ya cifrados en BD.
REPOSITORY_ENCRYPTION_KEY = os.environ.get('REPOSITORY_ENCRYPTION_KEY', '')

# Geocodificación (búsqueda de direcciones / geocodificación inversa).
# Proveedor por defecto: Nominatim (OpenStreetMap). Cambiar la URL base aquí
# (o vía .env) permite apuntar a otro proveedor sin tocar el código de
# geolocation/services.py.
NOMINATIM_BASE_URL = os.environ.get('NOMINATIM_BASE_URL', 'https://nominatim.openstreetmap.org')
NOMINATIM_USER_AGENT = os.environ.get(
    'NOMINATIM_USER_AGENT', 'AgriVisionOS/1.0 (+https://github.com/agrovision)'
)

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True,
)
