"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import cloudinary
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variables de entorno — vive en agrovision_backend/.env (junto a manage.py),
# no se versiona (ver .gitignore / .env.example). BASE_DIR ya apunta a
# agrovision_backend/, así que esta ruta es correcta tal como está.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# DEBUG primero: SECRET_KEY y otras validaciones dependen de si estamos en
# desarrollo (permite un fallback no sensible) o producción (exige el real).
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        # Válido solo para desarrollo local — no es un secreto real.
        SECRET_KEY = "django-insecure-local-development-only"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY es obligatorio cuando DJANGO_DEBUG no está activo "
            "(producción). Defínelo como variable de entorno."
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver"
    ).split(",")
    if host.strip()
]

# Subdominios de Vercel (preview y producción) — Django trata un valor con
# punto inicial como comodín de subdominio.
ALLOWED_HOSTS.append(".vercel.app")

# Vercel expone la URL del despliegue actual sin esquema (p. ej.
# "mi-app.vercel.app") en VERCEL_URL — se agrega tal cual si está presente.
_vercel_url = os.environ.get("VERCEL_URL")
if _vercel_url:
    ALLOWED_HOSTS.append(_vercel_url.replace("https://", "").replace("http://", ""))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'authtoken',
    'cultivos',
    'lotes',
    'metricas',
    'archivos',
    'ml_models',
    'ubicaciones',
    'repository',
    'geolocation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # sirve estáticos en producción sin depender del hosting
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Dos escenarios, nunca mezclados:
# - DATABASE_URL presente (producción) -> tiene prioridad, vía dj-database-url.
# - DATABASE_URL ausente (desarrollo local) -> variables POSTGRES_DB/
#   POSTGRES_USER/POSTGRES_PASSWORD/POSTGRES_HOST/POSTGRES_PORT, con
#   validación explícita si falta alguna. Nunca cae a SQLite en silencio.

_database_url = os.environ.get("DATABASE_URL")

if _database_url:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    _required_db_vars = ["POSTGRES_DB", "POSTGRES_USER", "POSTGRES_PASSWORD"]
    _missing_db_vars = [var for var in _required_db_vars if not os.environ.get(var)]
    if _missing_db_vars:
        raise ImproperlyConfigured(
            "Faltan variables de base de datos en tu .env: "
            f"{', '.join(_missing_db_vars)}. Defínelas ahí, o define DATABASE_URL "
            "para usar una cadena de conexión completa en su lugar."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic — necesario para servir estáticos en producción

# WhiteNoise + almacenamiento con hash/compresión para cache-busting seguro.
# Storage único para Django 6 (reemplaza el viejo STATICFILES_STORAGE).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Nota: MEDIA_ROOT es solo un directorio local (útil en desarrollo); el
# repositorio real de imágenes agrícolas es Cloudinary (ver app 'repository')
# precisamente porque el filesystem de un despliegue serverless como Vercel
# es efímero y no debe usarse como almacenamiento persistente.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

ML_CHECKPOINTS_DIR = BASE_DIR / 'ml_models' / 'checkpoints'

# CORS — orígenes del frontend permitidos para llamar a la API. En producción,
# reemplaza la variable de entorno completa por la URL real (ver .env.example).
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000"
    ).split(",")
    if origin.strip()
]

# Extra de conveniencia: si defines FRONTEND_URL (por ejemplo porque todavía
# no quieres reescribir la lista completa de CORS_ALLOWED_ORIGINS), se agrega
# igual sin tener que repetirla en dos variables distintas.
_frontend_url = os.environ.get("FRONTEND_URL")
if _frontend_url and _frontend_url.rstrip("/") not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(_frontend_url.rstrip("/"))

# El login usa sesión Django (cookie 'sessionid'), no tokens — las
# credenciales (cookies) deben viajar en los requests cross-origin.
CORS_ALLOW_CREDENTIALS = True

# Authentication redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Sesión Django
SESSION_COOKIE_HTTPONLY = True  # La cookie no es accesible desde JavaScript

# SameSite: la autenticación actual es 100% por cookie de sesión (no hay
# tokens), y este proyecto despliega frontend y backend como dos servicios
# *separados* (dominios/subdominios distintos) — eso es cross-site para el
# navegador. "Lax" (el default de Django) NO se envía en esas requests
# cross-origin, así que el login quedaría roto en producción si se dejara
# fijo. En local, frontend y backend comparten "localhost" (incluida cookie
# SameSite=Lax entre puertos), así que ahí "Lax" sigue funcionando sin tocar
# nada. Por eso la decisión es condicional a DEBUG, no un valor fijo:
SESSION_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
CSRF_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
# SameSite=None exige Secure=True (si no, el navegador descarta la cookie) —
# ya es así, porque estas dos ya son not DEBUG independientemente de lo anterior.
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS obligatorio para la cookie fuera de desarrollo
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 días en segundos

CSRF_COOKIE_SECURE = not DEBUG

# CSRF — orígenes de confianza para requests cross-origin con credenciales.
# A diferencia de CORS_ALLOWED_ORIGINS, Django exige esquema (http/https).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000"
    ).split(",")
    if origin.strip()
]
if _frontend_url and _frontend_url.rstrip("/") not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_frontend_url.rstrip("/"))

_backend_url = os.environ.get("BACKEND_URL")
if _backend_url and _backend_url.rstrip("/") not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_backend_url.rstrip("/"))

# Necesario detrás de un proxy HTTPS (Vercel, Railway, Render, etc.): sin
# esto, Django no reconoce que el request original llegó por HTTPS y las
# cookies "Secure" nunca se devuelven en producción.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Redirección forzada a HTTPS — apagada por defecto porque muchos hostings
# (incluido Vercel) ya la manejan en su propio proxy/edge; actívala solo si
# tu hosting específico no lo hace y confirmas que no genera loops de
# redirección con el proxy.
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "False").lower() == "true"

# Cloudinary — repositorio externo de imágenes (ver app 'repository').
# Las claves viven únicamente aquí (backend); nunca se exponen al frontend.
#
# Estas variables son OPCIONALES: cada usuario configura su propio
# repositorio desde la interfaz (modelo RepositorioImagen, cifrado en BD).
# Si se completan aquí, actúan solo como repositorio de fallback para
# usuarios que todavía no configuraron uno propio — ver
# repository/providers/factory.py::get_provider_for_user(). Un despliegue
# nuevo puede dejarlas vacías sin que el sistema falle al arrancar.
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '')

# CLOUDINARY_DEFAULT_FOLDER: valor inicial opcional para el repositorio de
# fallback de arriba — no es la fuente de verdad de "qué carpeta sincronizar".
# La carpeta real se elige desde la interfaz (selector "Actualizar carpetas"
# en el módulo Repositorio, que consulta Cloudinary en vivo) y se guarda por
# usuario en RepositorioImagen.carpeta_raiz (PostgreSQL) — crear una carpeta
# nueva en Cloudinary y sincronizarla nunca requiere tocar este .env ni
# reiniciar el backend. Se acepta también el nombre histórico
# CLOUDINARY_FOLDER para no romper despliegues existentes.
CLOUDINARY_FOLDER = os.environ.get('CLOUDINARY_DEFAULT_FOLDER') or os.environ.get('CLOUDINARY_FOLDER', 'agrovision')

# Clave de cifrado dedicada para RepositorioImagen.api_secret (opcional).
# Si se omite, se deriva de SECRET_KEY (ver repository/encryption.py) — fijar
# una propia en producción permite rotar SECRET_KEY sin perder los secretos
# ya cifrados en BD.
REPOSITORY_ENCRYPTION_KEY = os.environ.get('REPOSITORY_ENCRYPTION_KEY', '')

# Geocodificación (búsqueda de direcciones / geocodificación inversa).
# Proveedor por defecto: Nominatim (OpenStreetMap). Cambiar la URL base aquí
# (o vía .env) permite apuntar a otro proveedor sin tocar el código de
# geolocation/services.py.
NOMINATIM_BASE_URL = os.environ.get('NOMINATIM_BASE_URL', 'https://nominatim.openstreetmap.org')
NOMINATIM_USER_AGENT = os.environ.get(
    'NOMINATIM_USER_AGENT', 'AgriVisionOS/1.0 (+https://github.com/agrovision)'
)

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True,
)
