# Generated by Django 6.0.4 on 2026-08-06 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='source',
            field=models.CharField(choices=[('DEVICE_GEOLOCATION', 'Ubicación del dispositivo'), ('ADDRESS_SEARCH', 'Búsqueda de dirección'), ('MAP_SELECTION', 'Selección en el mapa')], max_length=30),
        ),
    ]
